In [1]:
#Importing Necessary Libraries
import numpy #used for numerical analysis
import tensorflow #open source used for both NL and DL for computation
from tensorflow.keras.datasets import mnist #mnist datoser
from tensorflow.keras.models import Sequential #it is a plain stack of Layers
from tensorflow.keras import layers #A Layer consists of a tensor-in tensor-out computation function
from tensorflow.keras.layers import Dense, Flatten #Dense-Dense Layer is the regular deeply connected
#Faltten-used for flattening the input or change the dimension
from tensorflow.keras.layers import Conv2D #Convolutional Layer
from keras.optimizers import Adam #optimizer
from keras.utils import np_utils #used for one-hot encoding

In [2]:
#load data
(x_train, y_train), (x_test, y_test)=mnist.load_data() #splitting the mist data into train and test

In [3]:
print(x_train.shape) #shope is used for give the dimension values #60000-rows 28x28-pixels
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
#Understanding the data
x_train[0] #printing the first image


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
#Reshaping Dataset
#Reshaping to format which CNN expects (batch, height, width, channels) 
x_train = x_train.reshape(60000, 28, 28, 1).astype('float32') 
x_test = x_test.reshape(10000, 28, 28, 1).astype('float32')

In [6]:
#One-Hot Encoding
#one hot encode
number_of_classes = 10 #storing the no. classes in a variable
y_train = np_utils.to_categorical (y_train, number_of_classes) #converts the output in binary format
y_test = np_utils.to_categorical (y_test, number_of_classes)

In [7]:
y_train[0] #printing the new Label


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [8]:
#Creating the Model
#create model
model = Sequential()
#adding model Layer
model.add(Conv2D (64, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D (32, (3, 3), activation='relu'))
#model.add(Conv20(32, (3, 3), activation="relu"))
#flotten the dimension of the image
model.add(Flatten())
#output Layer with 10 neurons
model.add(Dense(number_of_classes, activation='softmax'))

In [9]:
#Compiling the model
#Compile model
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

In [10]:
# Fitting the model
# Fit the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=32)


Epoch 1/5
1875/1875 [==============================] - 145s 76ms/step - loss: 0.2314 - accuracy: 0.9524 - val_loss: 0.1063 - val_accuracy: 0.9702
Epoch 2/5
1875/1875 [==============================] - 216s 115ms/step - loss: 0.0705 - accuracy: 0.9782 - val_loss: 0.0900 - val_accuracy: 0.9732
Epoch 3/5
1875/1875 [==============================] - 211s 112ms/step - loss: 0.0502 - accuracy: 0.9837 - val_loss: 0.0905 - val_accuracy: 0.9712
Epoch 4/5
1875/1875 [==============================] - 142s 76ms/step - loss: 0.0384 - accuracy: 0.9876 - val_loss: 0.0768 - val_accuracy: 0.9779
Epoch 5/5
1875/1875 [==============================] - 137s 73ms/step - loss: 0.0286 - accuracy: 0.9910 - val_loss: 0.1094 - val_accuracy: 0.9759


In [11]:
#Observing the metrics
# Final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0) 
print("Metrics (Test loss & Test Accuracy): ")
print(metrics)

Metrics (Test loss & Test Accuracy): 
[0.10939381271600723, 0.9758999943733215]


In [12]:
#Predicting the output
prediction=model.predict(x_test[:4])
print (prediction)

1/1 [==============================] - 0s 202ms/step
[[2.98307223e-13 1.31639574e-17 5.07505010e-11 2.12741336e-09
  2.55904906e-16 3.28386653e-16 1.14010902e-20 1.00000000e+00
  1.51029485e-13 2.43428333e-11]
 [1.09271386e-05 1.28598532e-09 9.99971390e-01 7.52625454e-07
  2.02695357e-14 2.48325180e-11 1.69312589e-05 4.04112802e-16
  1.32878535e-08 6.94642572e-14]
 [4.80226081e-10 9.99881744e-01 5.07329123e-10 2.65095476e-12
  1.17919721e-04 7.50208002e-08 1.01075252e-10 8.24279844e-09
  2.82054032e-07 1.74153701e-14]
 [9.99999762e-01 2.83770225e-16 2.06525162e-11 7.26806192e-15
  2.15151399e-12 2.20106089e-09 2.83147358e-07 1.23577621e-13
  3.60704110e-12 1.13901146e-08]]


In [13]:
import numpy as np
print (np.argmax(prediction, axis=1)) #printing our labels from first 4 images
print (y_test[:4]) #printing the actual labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
#Observing the metrics
# Final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics (Test loss & Test Accuracy): ")
print(metrics)


Metrics (Test loss & Test Accuracy): 
[0.10939381271600723, 0.9758999943733215]


In [15]:
#Predicting the output
prediction=model.predict(x_test[:4])
print (prediction)

1/1 [==============================] - 0s 75ms/step
[[2.98307223e-13 1.31639574e-17 5.07505010e-11 2.12741336e-09
  2.55904906e-16 3.28386653e-16 1.14010902e-20 1.00000000e+00
  1.51029485e-13 2.43428333e-11]
 [1.09271386e-05 1.28598532e-09 9.99971390e-01 7.52625454e-07
  2.02695357e-14 2.48325180e-11 1.69312589e-05 4.04112802e-16
  1.32878535e-08 6.94642572e-14]
 [4.80226081e-10 9.99881744e-01 5.07329123e-10 2.65095476e-12
  1.17919721e-04 7.50208002e-08 1.01075252e-10 8.24279844e-09
  2.82054032e-07 1.74153701e-14]
 [9.99999762e-01 2.83770225e-16 2.06525162e-11 7.26806192e-15
  2.15151399e-12 2.20106089e-09 2.83147358e-07 1.23577621e-13
  3.60704110e-12 1.13901146e-08]]


In [16]:
import numpy as np
print (np.argmax(prediction, axis=1)) #printing our labels from first 4 images
print (y_test[:4]) #printing the actual labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
#Saving the model
# Save the model
model.save('mnistCNN.h5')

In [34]:
#Importing the Keras Libraries and packages
from tensorflow.keras.models import load_model
model = load_model(r'C:\Users\Mano\OneDrive\Desktop\New folder\mnistCNN.h5') 
from PIL import Image #used for manipulating image uploaded by the user.
import numpy as np #used for numerical analysis
for index in range(4):
    img = Image.open(r'C:\Users\Mano\OneDrive\Desktop\New folder\testSet\img_2.jpg') #convert image to monochrome
    img = img.resize((28,28))# resizing of input image
    im2arr= np.array(img) #converting to image
    im2arr = im2arr.reshape(1,28,28,1) #reshaping according to our requirement
#Predicting the Test set results
    y_pred= model.predict(im2arr) #predicting the results
    print(y_pred)


1/1 [==============================] - 0s 323ms/step
[[9.99798238e-01 6.69101656e-13 8.76860431e-05 2.05635217e-07
  3.78233957e-13 1.10077644e-05 9.23489206e-05 1.10451925e-10
  1.63557516e-07 1.03675184e-05]]
1/1 [==============================] - 0s 60ms/step
[[9.99798238e-01 6.69101656e-13 8.76860431e-05 2.05635217e-07
  3.78233957e-13 1.10077644e-05 9.23489206e-05 1.10451925e-10
  1.63557516e-07 1.03675184e-05]]
1/1 [==============================] - 0s 60ms/step
[[9.99798238e-01 6.69101656e-13 8.76860431e-05 2.05635217e-07
  3.78233957e-13 1.10077644e-05 9.23489206e-05 1.10451925e-10
  1.63557516e-07 1.03675184e-05]]
1/1 [==============================] - 0s 63ms/step
[[9.99798238e-01 6.69101656e-13 8.76860431e-05 2.05635217e-07
  3.78233957e-13 1.10077644e-05 9.23489206e-05 1.10451925e-10
  1.63557516e-07 1.03675184e-05]]
