In [2]:
#Importing Necessary Libraries
import numpy #used for numerical analysis
import tensorflow #open source used for both NL and DL for computation
from tensorflow.keras.datasets import mnist #mnist datoser
from tensorflow.keras.models import Sequential #it is a plain stack of Layers
from tensorflow.keras import layers #A Layer consists of a tensor-in tensor-out computation function
from tensorflow.keras.layers import Dense, Flatten #Dense-Dense Layer is the regular deeply connected
#Faltten-used for flattening the input or change the dimension
from tensorflow.keras.layers import Conv2D #Convolutional Layer
from keras.optimizers import Adam #optimizer
from keras.utils import np_utils #used for one-hot encoding

In [3]:
#load data
(x_train, y_train), (x_test, y_test)=mnist.load_data() #splitting the mist data into train and test

In [4]:
print(x_train.shape) #shope is used for give the dimension values #60000-rows 28x28-pixels
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [5]:
#Understanding the data
x_train[0] #printing the first image


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
#Reshaping Dataset
#Reshaping to format which CNN expects (batch, height, width, channels) 
x_train = x_train.reshape(60000, 28, 28, 1).astype('float32') 
x_test = x_test.reshape(10000, 28, 28, 1).astype('float32')

In [7]:
#One-Hot Encoding
#one hot encode
number_of_classes = 10 #storing the no. classes in a variable
y_train = np_utils.to_categorical (y_train, number_of_classes) #converts the output in binary format
y_test = np_utils.to_categorical (y_test, number_of_classes)

In [8]:
y_train[0] #printing the new Label


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [9]:
#Creating the Model
#create model
model = Sequential()
#adding model Layer
model.add(Conv2D (64, (3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D (32, (3, 3), activation='relu'))
#model.add(Conv20(32, (3, 3), activation="relu"))
#flotten the dimension of the image
model.add(Flatten())
#output Layer with 10 neurons
model.add(Dense(number_of_classes, activation='softmax'))

In [10]:
#Compiling the model
#Compile model
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=['accuracy'])

In [11]:
# Fitting the model
# Fit the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=32)


Epoch 1/5
1875/1875 [==============================] - 115s 61ms/step - loss: 0.2578 - accuracy: 0.9485 - val_loss: 0.1010 - val_accuracy: 0.9679
Epoch 2/5
1875/1875 [==============================] - 142s 76ms/step - loss: 0.0746 - accuracy: 0.9775 - val_loss: 0.0954 - val_accuracy: 0.9751
Epoch 3/5
1875/1875 [==============================] - 129s 69ms/step - loss: 0.0516 - accuracy: 0.9837 - val_loss: 0.1055 - val_accuracy: 0.9709
Epoch 4/5
1875/1875 [==============================] - 124s 66ms/step - loss: 0.0384 - accuracy: 0.9877 - val_loss: 0.0970 - val_accuracy: 0.9762
Epoch 5/5
1875/1875 [==============================] - 119s 63ms/step - loss: 0.0297 - accuracy: 0.9905 - val_loss: 0.1252 - val_accuracy: 0.9707


In [12]:
#Observing the metrics
# Final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0) 
print("Metrics (Test loss & Test Accuracy): ")
print(metrics)

Metrics (Test loss & Test Accuracy): 
[0.12518303096294403, 0.9707000255584717]


In [13]:
#Predicting the output
prediction=model.predict(x_test[:4])
print (prediction)

1/1 [==============================] - 0s 136ms/step
[[6.6364265e-08 5.3783553e-14 2.9456195e-09 5.9538001e-09 1.1636773e-13
  6.9720341e-12 1.3643049e-16 9.9999952e-01 3.3651872e-07 2.8203598e-08]
 [6.9063418e-08 5.4751903e-10 9.9995852e-01 5.5559729e-10 1.8669308e-13
  7.1107349e-15 4.0646722e-05 2.2787508e-16 6.6394551e-07 1.6928877e-16]
 [1.2913587e-08 9.9986243e-01 5.7425777e-06 6.0556102e-11 6.7877806e-07
  6.8332033e-06 7.8326693e-08 8.7100647e-09 1.2423341e-04 1.1543968e-10]
 [9.9999404e-01 1.2942625e-13 4.1105155e-09 6.2053726e-13 2.5306660e-10
  1.1673318e-10 2.8591307e-06 1.3371672e-12 2.8005941e-06 3.5584372e-07]]


In [14]:
import numpy as np
print (np.argmax(prediction, axis=1)) #printing our labels from first 4 images
print (y_test[:4]) #printing the actual labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
#Observing the metrics
# Final evaluation of the model
metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics (Test loss & Test Accuracy): ")
print(metrics)


Metrics (Test loss & Test Accuracy): 
[0.12518303096294403, 0.9707000255584717]


In [16]:
#Predicting the output
prediction=model.predict(x_test[:4])
print (prediction)

1/1 [==============================] - 0s 29ms/step
[[6.6364265e-08 5.3783553e-14 2.9456195e-09 5.9538001e-09 1.1636773e-13
  6.9720341e-12 1.3643049e-16 9.9999952e-01 3.3651872e-07 2.8203598e-08]
 [6.9063418e-08 5.4751903e-10 9.9995852e-01 5.5559729e-10 1.8669308e-13
  7.1107349e-15 4.0646722e-05 2.2787508e-16 6.6394551e-07 1.6928877e-16]
 [1.2913587e-08 9.9986243e-01 5.7425777e-06 6.0556102e-11 6.7877806e-07
  6.8332033e-06 7.8326693e-08 8.7100647e-09 1.2423341e-04 1.1543968e-10]
 [9.9999404e-01 1.2942625e-13 4.1105155e-09 6.2053726e-13 2.5306660e-10
  1.1673318e-10 2.8591307e-06 1.3371672e-12 2.8005941e-06 3.5584372e-07]]


In [17]:
import numpy as np
print (np.argmax(prediction, axis=1)) #printing our labels from first 4 images
print (y_test[:4]) #printing the actual labels

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
#Saving the model
# Save the model
model.save('mnistCNN.h5')

In [20]:
#Taking images as input and checking results
#Importing the Keras Libraries and packages
from tensorflow.keras.models import load_model
model = load_model(r'C:\Users\Mano\OneDrive\Desktop\New folder\mnistCNN.h5') 
from PIL import Image#used for manipulating image uploaded by the user.
import numpy as np#used for numerical analysis
for index in range(4):
 img = Image.open('data/' + str(index) + '.png').convert("L") #convert image to monochrome
 img = img.resize((28,28))# resizing of input image
 im2arr=np.array(img) #converting to image
 im2arr = im2arr.reshape(1,28,28,1) #reshaping according to our requirement
 #Predicting the Test set results
 y_pred = model.predict(im2arr) #predicting the results
 print(y_pred)

FileNotFoundError: [Errno 2] No such file or directory: 'data/0.png'